### PR TITLE
Adding useful Python libraries to default BBB and MBM2 configs

### PR DESCRIPTION
**Pull request by CatGarab**

### CODE REVIEW

**Comment by CatGarab** [comment]
[KLB: Add Python libraries for peripherals](https://trello.com/c/EjwrA2if/687-klb-add-python-libraries-for-peripherals)

**Comment by CatGarab** [comment]
[Put NumPy in kubOS](https://trello.com/c/tId88Xbn/822-put-numpy-in-kubos)

**Comment by CatGarab** [comment]
[Create KLB packages for Kubos Python libraries](https://trello.com/c/q5Z99tOz/412-create-klb-packages-for-kubos-python-libraries)

**Comment by plauche** [comment]
The CI build error
```
mkfs.ext4: Could not allocate block in ext2 filesystem while populating file system
*** Maybe you need to increase the filesystem size (BR2_TARGET_ROOTFS_EXT2_SIZE)
```
Is this something we see randomly or is it related to installing more python packages in the rootfs?

**Comment by CatGarab** [comment]
@plauche That error is something we'll see now due the buildroot upgrade. The rootfs used to be automatically sized. The size now has to be manually defined.
This worked successfully in the other PR because we just happened to be below the default size (60MB)

**Pull request merged**
